services:
  mongo:
    image: mongo:6.0
    container_name: gs-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  core_service:
    build:
      context: ./services/core_service
    container_name: gs-core_service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongo

  crawl-service:
    build:
      context: ./services/crawl-service
    container_name: gs-crawl-service
    env_file:
      - ./services/crawl-service/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "8001:8000"
    depends_on:
      - mongo
      - redis

  celery_worker: # Celery 워커 서비스 추가
    build:
      context: ./services/crawl-service
    container_name: gs-celery-worker
    command: celery -A crawl_service worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - crawl-service
      - kafka
    volumes:
      - .:/app/crawl-service
    restart: always

  kafka_consumer:
    build:
      context: ./services/crawl-service
    container_name: gs-kafka-consumer
    command: python news/views/kafka_consumer.py
    depends_on:
      - kafka
      - redis
      - mongo
      - crawl-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=crawl_service.settings
      - PYTHONPATH=/app/crawl-service
    volumes:
      - ./services/crawl-service:/app/crawl-service
    restart: always

  market-service:
    build:
      context: ./services/market-service
    container_name: gs-market-service
    env_file:
      - ./services/market-service/.env
    ports:
      - "8002:8000"

  search-service:
    build:
      context: ./services/search-service
    container_name: gs-search-service
    env_file:
      - ./services/search-service/.env
    ports:
      - "8003:8000"

  finance-service:
    build:
      context: ./services/finance-service
    container_name: gs-finance-service
    env_file:
      - ./services/finance-service/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8004:8000"

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - crawl-service
      - market-service
      - search-service
      - finance-service
      - core_service
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
volumes:
  mongo_data: