events { }

http {
    upstream core_service {
        server core_service:8080;
    }

    upstream crawl_service {
        server crawl-service:8000;
    }

    upstream market_service {
        server market-service:8000;
    }

    upstream search_service {
        server search-service:8000;
    }

    upstream finance_service {
        server finance-service:8000;
    }

    server {
        listen 80;

        location /core/ {
            proxy_pass http://core_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /crawl/ {
            proxy_pass http://crawl_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /market/ {
            proxy_pass http://market_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /search/ {
            proxy_pass http://search_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /finance/ {
            proxy_pass http://finance_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
